import "@/styles/globals.css";
import Head from "next/head";
import { useState, useEffect } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import store from "@/store/store";
import LoadingBar from "react-top-loading-bar";
import { NextUIProvider } from "@nextui-org/react";
import { useRouter } from "next/router";
import AnimatedCursor from "react-animated-cursor";
export default function App({ Component, pageProps, emotionCache }) {
  const router = useRouter();
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    // START VALUE - WHEN LOADING WILL START
    router.events.on("routeChangeStart", () => {
      setProgress(40);
    });

    // COMPLETE VALUE - WHEN LOADING IS FINISHED
    router.events.on("routeChangeComplete", () => {
      setProgress(100);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Eye Tee | E-Store </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <AnimatedCursor
        innerSize={8}
        outerSize={25}
        innerScale={1}
        outerScale={2}
        outerAlpha={0}
        hasBlendMode={true}
        innerStyle={{
          backgroundColor: "black",
        }}
        outerStyle={{
          border: "1px solid black",
        }}
      />

      <Provider store={store}>
        <NextUIProvider>
          <Header />
          <LoadingBar
            color="rgb(0, 0, 0)"
            height={7}
            progress={progress}
            waitingTime={400}
            onLoaderFinished={() => {
              setProgress(0);
            }}
          />
          <Component {...pageProps} />
          <Footer />
        </NextUIProvider>
      </Provider>
    </>
  );
}
